name: tests

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      APP_PORT: 3000
      DB_HOST: 0.0.0.0
      DB_PORT: 3306
      DB_NAME: example_db
      DB_USER: root
      DB_PASS: example
      DB_ROOT_PASS: root
      JWT_ACCESS_TOKEN_EXP_IN_SEC: 3600
      JWT_REFRESH_TOKEN_EXP_IN_SEC: 7200
      JWT_PUBLIC_KEY_BASE64: ${{ secrets.JWT_PUBLIC_KEY_BASE64 }}
      JWT_PRIVATE_KEY_BASE64: ${{ secrets.JWT_PRIVATE_KEY_BASE64 }}
      DEFAULT_ADMIN_USER_PASSWORD: example_admin_pass
      REDIS_HOST: 0.0.0.0
      REDIS_PORT: 6379
      REDIS_PASSWORD: redispw
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: 25
      MAIL_USER: example
      MAIL_PASSWORD: secret
      MAIL_FROM: noreply@example.com
      AWS_S3_ACCESS_KEY: minioadmin
      AWS_S3_SECRET_KEY: minioadmin
      AWS_S3_ENDPOINT: http://0.0.0.0:9000
      AWS_S3_BUCKET: main-bucket
      AWS_S3_REGION: eu-central-1

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml up -d mysqldb redis minio
      - name: Check running containers
        run: docker ps -a
      - name: Run e2e tests
        run: sleep 5 && npm run test:e2e
